# Site settings
title: The Invasive Species Project
email: nickcwilkins@yahoo.com
description:  We created this project to offer some information about the seemingly native insects, plants, animals etc., that are probably not so native at all.
              In fact, here are hundreds of Invasive species in the United States, and they do huge amounts of agricultural damage which translates into big economic impacts.
              Read on to learn a bit about invasive species near you and why you should care about them.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://invasivespeciesproject.github.io" # the base hostname & protocol for your site

analytics_id: UA-99110270-1
# Build settings
markdown: kramdown
